# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d48e37b540e86a9cd4a1ccbd422c602e55d98933d9ecde62073ca3768a20bbe88b4024e1752fcc5485435d93f9225690b479700c15b85cca9cf5831e1d46c73

test:
  secret_key_base: 01de8e5be65542621f3a77aeefc35abac1195d5a16b9578f02784dd0671ac3d2834e7e4f56bedbd0189114510f9e3bb0b50bb7b964ebb50472b762598169347c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
